import React, { useEffect, useRef } from "react";

const Divider = () => {
    const containerRef = useRef(null);

    // array teks dan elemen i
    const content = [
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
        "Web Development",
        "Product Design",
        "Software Development",
        "Landing Pages",
        "SaaS",
        "AI Automation",
    ];

    const handleLooping = () => {
        const container = containerRef.current;

        //    cek kkalo elemen terakhir udah di luar 
        if (container) {
            const lastSpan = container.lastChild;

            // kalo  elemen terakhir adalah span dan sudah keluar dari layar
            if (lastSpan && lastSpan.offsetLeft + lastSpan.clientWidth <= 0) {
                const firstSpan = container.firstChild;
                container.appendChild(firstSpan); //trus tambahin span pertama ke terakhir
            }
        }
    };

    useEffect(() => {
        //interval looping
        const intervalId = setInterval(() => {
            handleLooping();
        }, 1);

        return () => {
            clearInterval(intervalId);
        };
    }, []);

    return (
        <div
            id="divider"
            className="relative flex items-center justify-center w-full h-16 px-4 overflow-hidden md:py-2 sm:px-2 bg-bg-default-tertiary xl:text-xl"
        >
            <div
                ref={containerRef}
                className="flex items-center gap-9 md:m-0 whitespace-nowrap animate-marquee"
            >
                {content.map((item, index) => (
                    <React.Fragment key={index}>
                        <span className="text-white">{item}</span>
                        <i className="fa-solid fa-circle text-icon-brand-tertiary"></i>
                    </React.Fragment>
                ))}
            </div>
        </div>
    );
};

export default Divider;
